import os
import json
import urllib.request
from datetime import datetime

class SlackNotifier:
    def __init__(self):
        self.webhook_url = os.environ.get("SLACK_WEBHOOK_URL")
        self.log_file = "slack_notifications.log"

    def send_critical_alert(self, file_path: str, title: str, category: str, severity: str, explanation: str, suggestion: str = None) -> bool:
        """
        Constructs and dispatches a Slack Block Kit notification for critical issues.
        """
        # Format emoji based on severity
        icon = "🚨" if severity.lower() == "critical" else "⚠️"
        
        # Build blocks
        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"{icon} High-Severity Review Alert",
                    "emoji": True
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*File:* `{file_path}`\n*Category:* `{category.upper()}` | *Severity:* `{severity.upper()}`"
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Issue:* *{title}*\n{explanation}"
                }
            }
        ]

        if suggestion:
            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Suggested Fix Code*:\n```python\n{suggestion}\n```"
                }
            })
            
        blocks.append({
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"Generated by Autonomous AI Code Review Agent • {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
                }
            ]
        })

        payload = {"blocks": blocks}

        # If webhook is not configured, fall back to logging the message
        if not self.webhook_url:
            self._log_locally(payload)
            return False

        try:
            req = urllib.request.Request(
                self.webhook_url,
                data=json.dumps(payload).encode('utf-8'),
                headers={'Content-Type': 'application/json'},
                method='POST'
            )
            with urllib.request.urlopen(req) as response:
                return response.status == 200
        except Exception as e:
            print(f"Error dispatching Slack alert: {e}")
            self._log_locally(payload)
            return False

    def _log_locally(self, payload: dict):
        """
        Appends the notification payload to a local log file for testing/development.
        """
        timestamp = datetime.now().isoformat()
        log_entry = {
            "timestamp": timestamp,
            "payload": payload
        }
        try:
            with open(self.log_file, "a", encoding="utf-8") as f:
                f.write(json.dumps(log_entry) + "\n")
        except Exception as e:
            print(f"Failed to write Slack notification log: {e}")
